# Generated by Django 5.1.1 on 2024-09-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bis',
            fields=[
                ('idbis', models.AutoField(primary_key=True, serialize=False)),
                ('nomorbis', models.CharField(max_length=10)),
                ('jadwal', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='kelaslayanan',
            fields=[
                ('idkelaslayanan', models.AutoField(primary_key=True, serialize=False)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kapasitas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='layanantambahan',
            fields=[
                ('idlayanantambahan', models.AutoField(primary_key=True, serialize=False)),
                ('namalayanan', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='penumpang',
            fields=[
                ('idpenumpang', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('notelp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('umur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='detailkelaslayanan',
            fields=[
                ('iddetailkelaslayanan', models.AutoField(primary_key=True, serialize=False)),
                ('namakelaslayanan', models.CharField(max_length=100)),
                ('idbis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velos.bis')),
                ('idkelaslayanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velos.kelaslayanan')),
            ],
        ),
        migrations.CreateModel(
            name='pemesanan',
            fields=[
                ('idpemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('nomorkursi', models.CharField(max_length=10)),
                ('iddetailkelaslayanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velos.detailkelaslayanan')),
                ('idpenumpang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velos.penumpang')),
            ],
        ),
        migrations.CreateModel(
            name='detailpemesanan',
            fields=[
                ('iddetailpemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('idlayanantambahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velos.layanantambahan')),
                ('idpemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velos.pemesanan')),
            ],
        ),
    ]
