# Generated by Django 5.1.1 on 2024-09-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailkelaslayanan',
            name='namakelaslayanan',
        ),
        migrations.RemoveField(
            model_name='kelaslayanan',
            name='kapasitas',
        ),
        migrations.AddField(
            model_name='detailkelaslayanan',
            name='kapasitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kelaslayanan',
            name='namakelaslayanan',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
