# Generated by Django 5.1.1 on 2024-09-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velos', '0002_remove_detailkelaslayanan_namakelaslayanan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesanan',
            name='nomorkursi',
        ),
    ]
